package com.shahedrahim.mvvm;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

/**
 * This class is an Room Entity Table on the SQLite database
 * the tableName is note_table
 */
@Entity(tableName = "note_table")
public class Note {

    // Note id autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    private int id;

    // Note title
    private String title;

    // Note description
    private String description;

    // Note priority
    private int priority;

    /**
     * Constructor: creates the Note, and abstracts it into a row in the SQLite table
     * @param title
     * @param description
     * @param priority
     */
    public Note(String title, String description, int priority) {
        this.title = title;
        this.description = description;
        this.priority = priority;
    }

    /**
     * Setter method for id
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter method for Id
     * @return
     */
    public int getId() {
        return id;
    }

    /**
     * Getter method for Title
     * @return
     */
    public String getTitle() {
        return title;
    }

    /**
     * Getter method for description
     * @return
     */
    public String getDescription() {
        return description;
    }

    /**
     * Getter method for priority
     * @return
     */
    public int getPriority() {
        return priority;
    }
}
